# Generated by Django 5.2.7 on 2025-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
